apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/go4clouds/myapp:v2.0
        env:
        - name: MYAPP_PORT
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: port
        - name: MYAPP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: myapp
              key: message
